# Website: n/a
# Container: yourselfhosted/slash:latest
# GitHub: https://github.com/yourselfhosted/slash

services:
  slash:
    image: yourselfhosted/slash:latest
    container_name: slash
    restart: unless-stopped
    #ports:
      #- "5231:5231"
    volumes:
      - ${LOCALPATH}/slash/:/var/opt/slash
    environment:
      - TZ=${TZ}
    networks:
      - proxnet

  proxnet:
    external: true
    name: proxnet