# Website: https://uptime.kuma.pet/
# Container: https://hub.docker.com/r/louislam/uptime-kuma
# GitHub: https://github.com/louislam/uptime-kuma

services:
  uptime-kuma:
    image: 'louislam/uptime-kuma:2'
    container_name: uptime-kuma2
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ${LOCALPATH}/kuma2/_data:/app/data

networks:
  default:
    external: true
    name: proxnet
